---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/happilyc/public_html/allthingsxrpl.com/
    - /bin/cp dist/public/index.html $DEPLOYPATH
    - /bin/cp dist/public/robots.txt $DEPLOYPATH
    - /bin/cp dist/public/sitemap.xml $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp dist/public/favicon.png $DEPLOYPATH
    - /bin/cp dist/public/opengraph.jpg $DEPLOYPATH
    - /bin/cp -r dist/public/assets $DEPLOYPATH
    - /bin/cp -r dist/public/videos $DEPLOYPATH
