export interface BlogPostMeta {
  id: number;
  title: string;
  category: string;
  date: string;
  dateIso: string;
  titleKey: string;
  excerptKey: string;
  categoryKey: string;
  categoryLabelKey: string;
  readTimeKey: string;
  readTime: string;
  author: string;
  authorRole: string;
  image: string;
}

export const blogPosts: BlogPostMeta[] = [
  {
    id: 1,
    title: "Top 5 DeFi dApps on XRPL in 2026",
    category: "Ecosystem",
    date: "Jan 24, 2026",
    dateIso: "2026-01-24",
    titleKey: "blog.post1.title",
    excerptKey: "blog.post1.excerpt",
    categoryKey: "ecosystem",
    categoryLabelKey: "blog.post1.category",
    readTimeKey: "blog.readTime.5min",
    readTime: "5 min read",
    author: "Alex Crypto",
    authorRole: "Senior Analyst",
    image: "https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=400&auto=format&fit=crop",
  },
  {
    id: 2,
    title: "Understanding AMM Staking Rewards",
    category: "Guides",
    date: "Jan 20, 2026",
    dateIso: "2026-01-20",
    titleKey: "blog.post2.title",
    excerptKey: "blog.post2.excerpt",
    categoryKey: "guides",
    categoryLabelKey: "blog.post2.category",
    readTimeKey: "blog.readTime.8min",
    readTime: "5 min read",
    author: "Maya Chen",
    authorRole: "DeFi Researcher",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&auto=format&fit=crop",
  },
  {
    id: 3,
    title: "Security Best Practices for Self-Custody",
    category: "Security",
    date: "Jan 15, 2026",
    dateIso: "2026-01-15",
    titleKey: "blog.post3.title",
    excerptKey: "blog.post3.excerpt",
    categoryKey: "security",
    categoryLabelKey: "blog.post3.category",
    readTimeKey: "blog.readTime.4min",
    readTime: "5 min read",
    author: "Security Team",
    authorRole: "Cybersecurity Experts",
    image: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=400&auto=format&fit=crop",
  },
  {
    id: 4,
    title: "NFT Marketplaces on XRPL: Complete Guide",
    category: "NFTs",
    date: "Jan 12, 2026",
    dateIso: "2026-01-12",
    titleKey: "blog.post4.title",
    excerptKey: "blog.post4.excerpt",
    categoryKey: "nfts",
    categoryLabelKey: "blog.post4.category",
    readTimeKey: "blog.readTime.6min",
    readTime: "5 min read",
    author: "NFT Weekly",
    authorRole: "Digital Art Correspondent",
    image: "https://images.unsplash.com/photo-1643101809204-6fb869816dbe?w=400&auto=format&fit=crop",
  },
  {
    id: 5,
    title: "XRPL Sidechains Explained",
    category: "Technology",
    date: "Jan 8, 2026",
    dateIso: "2026-01-08",
    titleKey: "blog.post5.title",
    excerptKey: "blog.post5.excerpt",
    categoryKey: "technology",
    categoryLabelKey: "blog.post5.category",
    readTimeKey: "blog.readTime.7min",
    readTime: "5 min read",
    author: "Tech Deep Dive",
    authorRole: "Blockchain Developer",
    image: "https://images.unsplash.com/photo-1639762681057-408e52192e55?w=400&auto=format&fit=crop",
  },
  {
    id: 6,
    title: "Tokenizing Real World Assets on XRPL",
    category: "Institutional",
    date: "Jan 5, 2026",
    dateIso: "2026-01-05",
    titleKey: "blog.post6.title",
    excerptKey: "blog.post6.excerpt",
    categoryKey: "institutional",
    categoryLabelKey: "blog.post6.category",
    readTimeKey: "blog.readTime.9min",
    readTime: "5 min read",
    author: "Institutional Desk",
    authorRole: "Enterprise Analyst",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&auto=format&fit=crop",
  },
  {
    id: 7,
    title: "How to Stake XRP Safely in 2026",
    category: "Guides",
    date: "Jan 2, 2026",
    dateIso: "2026-01-02",
    titleKey: "blog.post7.title",
    excerptKey: "blog.post7.excerpt",
    categoryKey: "technology",
    categoryLabelKey: "blog.post7.category",
    readTimeKey: "blog.readTime.10min",
    readTime: "5 min read",
    author: "Dev Team",
    authorRole: "Protocol Engineers",
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&auto=format&fit=crop",
  },
  {
    id: 8,
    title: "XRPL vs Ethereum: Fees, Speed and Use Cases",
    category: "Analysis",
    date: "Dec 28, 2025",
    dateIso: "2025-12-28",
    titleKey: "blog.post8.title",
    excerptKey: "blog.post8.excerpt",
    categoryKey: "security",
    categoryLabelKey: "blog.post8.category",
    readTimeKey: "blog.readTime.5min",
    readTime: "5 min read",
    author: "Wallet Guide",
    authorRole: "Product Reviewer",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&auto=format&fit=crop",
  },
  {
    id: 9,
    title: "Choosing Between Hot and Cold Wallets",
    category: "Security",
    date: "Dec 22, 2025",
    dateIso: "2025-12-22",
    titleKey: "blog.post9.title",
    excerptKey: "blog.post9.excerpt",
    categoryKey: "institutional",
    categoryLabelKey: "blog.post9.category",
    readTimeKey: "blog.readTime.7min",
    readTime: "5 min read",
    author: "Banking Desk",
    authorRole: "Financial Correspondent",
    image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=400&auto=format&fit=crop",
  },
  {
    id: 10,
    title: "XRPL AMM Deep Dive for Liquidity Providers",
    category: "DeFi",
    date: "Dec 18, 2025",
    dateIso: "2025-12-18",
    titleKey: "blog.post10.title",
    excerptKey: "blog.post10.excerpt",
    categoryKey: "guides",
    categoryLabelKey: "blog.post10.category",
    readTimeKey: "blog.readTime.6min",
    readTime: "5 min read",
    author: "Tax Guide",
    authorRole: "Crypto Tax Specialist",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&auto=format&fit=crop",
  },
  {
    id: 11,
    title: "Beginner's Guide to Buying XRP",
    category: "Guides",
    date: "Dec 15, 2025",
    dateIso: "2025-12-15",
    titleKey: "blog.post11.title",
    excerptKey: "blog.post11.excerpt",
    categoryKey: "security",
    categoryLabelKey: "blog.post11.category",
    readTimeKey: "blog.readTime.5min",
    readTime: "5 min read",
    author: "Security Watch",
    authorRole: "Threat Analyst",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&auto=format&fit=crop",
  },
  {
    id: 12,
    title: "Top XRPL Tax Tools and Reporting Tips",
    category: "Guides",
    date: "Dec 10, 2025",
    dateIso: "2025-12-10",
    titleKey: "blog.post12.title",
    excerptKey: "blog.post12.excerpt",
    categoryKey: "technology",
    categoryLabelKey: "blog.post12.category",
    readTimeKey: "blog.readTime.8min",
    readTime: "5 min read",
    author: "Protocol Team",
    authorRole: "Network Engineer",
    image: "https://images.unsplash.com/photo-1622630998477-20aa696ecb05?w=400&auto=format&fit=crop",
  },
  {
    id: 13,
    title: "How XRPL Hooks Will Change Smart Contracts",
    category: "Technology",
    date: "Dec 5, 2025",
    dateIso: "2025-12-05",
    titleKey: "blog.post13.title",
    excerptKey: "blog.post13.excerpt",
    categoryKey: "ecosystem",
    categoryLabelKey: "blog.post13.category",
    readTimeKey: "blog.readTime.6min",
    readTime: "5 min read",
    author: "Ripple Watcher",
    authorRole: "Industry Analyst",
    image: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=400&auto=format&fit=crop",
  },
  {
    id: 14,
    title: "Cross-Border Payments Powered by XRPL",
    category: "Use Cases",
    date: "Dec 1, 2025",
    dateIso: "2025-12-01",
    titleKey: "blog.post14.title",
    excerptKey: "blog.post14.excerpt",
    categoryKey: "nfts",
    categoryLabelKey: "blog.post14.category",
    readTimeKey: "blog.readTime.7min",
    readTime: "5 min read",
    author: "Artist Spotlight",
    authorRole: "NFT Curator",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop",
  },
  {
    id: 15,
    title: "Setting Up Your First XRPL Trustline",
    category: "Guides",
    date: "Nov 28, 2025",
    dateIso: "2025-11-28",
    titleKey: "blog.post15.title",
    excerptKey: "blog.post15.excerpt",
    categoryKey: "guides",
    categoryLabelKey: "blog.post15.category",
    readTimeKey: "blog.readTime.10min",
    readTime: "5 min read",
    author: "Investment Team",
    authorRole: "Portfolio Analyst",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&auto=format&fit=crop",
  },
  {
    id: 16,
    title: "Hardware Wallet Buying Guide for XRP Holders",
    category: "Hardware",
    date: "Jan 26, 2026",
    dateIso: "2026-01-26",
    titleKey: "blog.post16.title",
    excerptKey: "blog.post16.excerpt",
    categoryKey: "technology",
    categoryLabelKey: "blog.post16.category",
    readTimeKey: "blog.readTime.12min",
    readTime: "5 min read",
    author: "DeFi Lab",
    authorRole: "Smart Contract Researcher",
    image: "https://images.unsplash.com/photo-1639762681057-408e52192e55?w=400&auto=format&fit=crop",
  },
  {
    id: 17,
    title: "Avoiding Common XRP Phishing Scams",
    category: "Security",
    date: "Jan 25, 2026",
    dateIso: "2026-01-25",
    titleKey: "blog.post17.title",
    excerptKey: "blog.post17.excerpt",
    categoryKey: "defi",
    categoryLabelKey: "blog.post17.category",
    readTimeKey: "blog.readTime.9min",
    readTime: "5 min read",
    author: "Risk Analyst",
    authorRole: "DeFi Security Expert",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&auto=format&fit=crop",
  },
  {
    id: 18,
    title: "XRPL Validator Network Explained",
    category: "Technology",
    date: "Jan 24, 2026",
    dateIso: "2026-01-24",
    titleKey: "blog.post18.title",
    excerptKey: "blog.post18.excerpt",
    categoryKey: "technology",
    categoryLabelKey: "blog.post18.category",
    readTimeKey: "blog.readTime.8min",
    readTime: "5 min read",
    author: "Yield Farmers",
    authorRole: "DeFi Strategist",
    image: "https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=400&auto=format&fit=crop",
  },
  {
    id: 19,
    title: "How to Track XRPL Wallet Activity",
    category: "Guides",
    date: "Jan 23, 2026",
    dateIso: "2026-01-23",
    titleKey: "blog.post19.title",
    excerptKey: "blog.post19.excerpt",
    categoryKey: "nfts",
    categoryLabelKey: "blog.post19.category",
    readTimeKey: "blog.readTime.10min",
    readTime: "5 min read",
    author: "NFT Technical",
    authorRole: "Protocol Developer",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop",
  },
];

export function getBlogPostById(id: number): BlogPostMeta | undefined {
  return blogPosts.find((p) => p.id === id);
}
